### ISSUE TITLE
could you share how to use

### ISSUE THREAD

**Issue by lewis15110** [ppoffice/lxc-android#4]
我猜大佬也是来自瓷器国的，就不用谷歌翻译粘英语了，能不能简单介绍下怎么使用呢，所有安卓9的设备都可以用吗？

**Comment by anthann** [comment]
checkout [01_Android_LXC_Note.md](https://gist.github.com/ppoffice/154acbc7fa6f8b73b7b3b57af3ca6951) for detail.

**Comment by ppoffice** [comment]
Please also refer to https://gist.github.com/ppoffice/2706b5e4448e8a3638c974e64c88c2ad
