### ISSUE TITLE
arm64 builds

### ISSUE THREAD

**Issue by Gouster4** [ppoffice/lxc-android#6]
Hi. Can you please make also builds for arm64 architecture?

I know that arm builds should work,
but with arm64 builds we can run arm64 os inside containers.

**Comment by ppoffice** [comment]
I don't see why this project won't compile to arm64

Please see if this helps: https://gist.github.com/ppoffice/2706b5e4448e8a3638c974e64c88c2ad

**Comment by Gouster4** [comment]
> I don't see why this project won't compile to arm64
> 
> Please see if this helps: https://gist.github.com/ppoffice/2706b5e4448e8a3638c974e64c88c2ad

Sorry, seems missunderstanding. Maybe my fault...

I mean if you can also provide arm64 builds along with arm builds which are available now from Jenkins.

**Comment by ppoffice** [comment]
Sorry, I don't offer binary releases since Android OSes, especially custom ROMs, are quite different from each other and my build will probably not work on others' phones.
